config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  resources :players



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@player = Player.all
  end

  def new
  	@player = Player.new
  end
  def create
  	@player = Player.new(player_params)
  	if @player.save
  		redirect_to root_path
  	end
  end

  def show
  	@player = Player.find_by(id: params[:id])
  end

  def edit
  	@player = Player.find_by(id: params[:id])
  end
  def update
	@player = Player.find_by(id: params[:id])
 	@player.update(player_params)
    if @player.save
      redirect_to player_path(@player.id)
    
    end
  	
  end
  def destroy
  	@player = Player.find(params[:id])
    @player.destroy
 
    redirect_to players_path
  end
    private
    def player_params
      params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: player_path(@player.id) do |f| %>
  Nickname: <%= f.text_field :nickname %><br />
  Rank : <%= f.text_field :rank %><br />
  Charisma : <%= f.text_field :charisma %><br />
  Wisdom : <%= f.text_field :wisdom %><br />
  <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<% if @player == [] %>
<p>We can`t show you any posts</p>
<%else %>
<% @player.each do |player| %>
<p>User: <b> <%= player.nickname %></br>write</br>
<%= player.rank %></br>
<%= player.charisma %></br>
<%= player.wisdom %></br>
 <%= link_to "More", player_path(player.id) %> 


<% end %>
<% end %>
 <%= link_to "New player", new_player_path %> 

app/views/players/new.html.erb
<%= form_for :player, url: players_path do |f| %>
  Nickname: <%= f.text_field :nickname %><br />
  Rank : <%= f.text_field :rank %><br />
  Charisma : <%= f.text_field :charisma %><br />
  Wisdom : <%= f.text_field :wisdom %><br />
  <%= f.submit %>
<% end %>

app/views/players/show.html.erb
 Nickname: <%= @player.nickname %><br />
rank: <%= @player.rank%><br />
charisma: <%= @player.charisma %><br />
wisdom: <%= @player.wisdom %><br />


<%= link_to "edit", edit_player_path(@player.id) %><br />
<%= link_to "destroy", player_path(@player.id), method: :delete %><br />